#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# setup_venv.sh  —  create the project venv and write config/paths.toml
#
# Run once per machine before using the COMSOL Simulation Suite MCP server.
# Safe to re-run: it skips venv creation if the venv already exists.
#
# Usage:
#   cd "COMSOL Simulation Suite"
#   bash setup_venv.sh
#
# What it does:
#   1. Creates /home/$USER/.venvs/chip_sim_suite/ with Python 3.11
#   2. Installs: mph, gdstk, JPype1, numpy, matplotlib + this package (editable)
#   3. Writes  config/paths.toml pointing python_bin at the new venv
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

VENV_DIR="/home/${USER}/.venvs/chip_sim_suite"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOML_OUT="${SCRIPT_DIR}/config/paths.toml"

echo "=== COMSOL Simulation Suite — venv setup ==="
echo "Venv location : ${VENV_DIR}"
echo "Config output : ${TOML_OUT}"
echo ""

# ── 1. Find Python 3.11 ──────────────────────────────────────────────────────
PYTHON=""
for candidate in python3.11 python3 python; do
    if command -v "${candidate}" &>/dev/null; then
        ver=$("${candidate}" --version 2>&1 | grep -oP '\d+\.\d+')
        major=$(echo "${ver}" | cut -d. -f1)
        minor=$(echo "${ver}" | cut -d. -f2)
        if [ "${major}" -ge 3 ] && [ "${minor}" -ge 11 ]; then
            PYTHON=$(command -v "${candidate}")
            echo "Using Python : ${PYTHON}  (${major}.${minor})"
            break
        fi
    fi
done

if [ -z "${PYTHON}" ]; then
    echo "ERROR: Python 3.11+ not found. Install it and try again." >&2
    exit 1
fi

# ── 2. Create venv (skip if already present) ─────────────────────────────────
if [ -f "${VENV_DIR}/bin/python" ]; then
    echo "Venv already exists — skipping creation."
else
    echo "Creating venv ..."
    mkdir -p "$(dirname "${VENV_DIR}")"
    "${PYTHON}" -m venv "${VENV_DIR}"
    echo "Venv created."
fi

PY="${VENV_DIR}/bin/python"
PIP="${VENV_DIR}/bin/pip"

# ── 3. Install dependencies ───────────────────────────────────────────────────
echo ""
echo "Installing packages ..."
"${PIP}" install --quiet --upgrade pip
# Install the suite itself (editable) plus the [comsol] extra (brings in mph).
"${PIP}" install --quiet -e "${SCRIPT_DIR}[comsol,dev]"
# Extra runtime deps used by the pipeline scripts.
"${PIP}" install --quiet matplotlib JPype1 scipy PyYAML
echo "Packages installed."

# ── 4. Verify key imports ─────────────────────────────────────────────────────
echo ""
echo "Verifying imports ..."
"${PY}" - <<'EOF'
import mph, gdstk, jpype, matplotlib, numpy, scipy, yaml
print(f"  mph        {mph.__version__}")
print(f"  gdstk      {gdstk.__version__}")
print(f"  jpype      {jpype.__version__}")
print(f"  matplotlib {matplotlib.__version__}")
print(f"  numpy      {numpy.__version__}")
print(f"  scipy      {scipy.__version__}")
print(f"  pyyaml     {yaml.__version__}")
EOF

# ── 5. Write config/paths.toml ────────────────────────────────────────────────
echo ""
echo "Writing ${TOML_OUT} ..."
mkdir -p "${SCRIPT_DIR}/config"
cat > "${TOML_OUT}" <<TOML
# ─────────────────────────────────────────────────────────────────────────────
# COMSOL Simulation Suite — machine paths
#
# Auto-generated by setup_venv.sh on $(date -I).
# This file is gitignored. Re-run setup_venv.sh to regenerate.
# ─────────────────────────────────────────────────────────────────────────────

# Python interpreter for all subprocess-launched pipeline scripts.
python_bin = "${VENV_DIR}/bin/python"

# Julia (optional — only for Josephson-circuit fitting).
# julia_bin = "/usr/local/bin/julia"

# COMSOL server (leave unset for local COMSOL via mph.start()).
# comsol_host = "comsol-server.lab.example"
# comsol_port = 2036

[scripts]
[data]
TOML

# ── 6. Patch .mcp.json to use the new venv ───────────────────────────────────
MCP_JSON="${SCRIPT_DIR}/../.mcp.json"
if [ -f "${MCP_JSON}" ]; then
    echo ""
    echo "Patching .mcp.json ..."
    # Replace the command line with the venv Python (any existing python path).
    python3 -c "
import json, re, sys
path = sys.argv[1]
venv_py = sys.argv[2]
with open(path) as f:
    data = json.load(f)
for srv in data.get('mcpServers', {}).values():
    if 'comsol' in srv.get('args', [''])[1] or 'comsol_suite' in str(srv.get('args',[])):
        srv['command'] = venv_py
with open(path, 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
print(f'  .mcp.json command → {venv_py}')
" "${MCP_JSON}" "${VENV_DIR}/bin/python"
else
    echo "  .mcp.json not found at ${MCP_JSON} — skipping."
fi

echo ""
echo "=== Setup complete ==="
echo ""
echo "IMPORTANT: Restart Claude Code (or reload the MCP server) for the new"
echo "Python to take effect."
echo ""
echo "The MCP server will now automatically use:"
echo "  ${VENV_DIR}/bin/python"
echo ""
echo "To verify:"
echo "  ${PY} -c \"import mph; print('mph ok')\""
